{
 "title": "HTTP Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "SHOW TAG VALUES WITH key = \"service\""
   },
   {
    "name": "application",
    "label": "Application",
    "query": "SHOW TAG VALUES WITH key = application"
   },
   {
    "name": "path",
    "label": "Endpoint",
    "query": "SHOW TAG VALUES WITH key = \"http_path\""
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_path",
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{http_path}}",
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_host, http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_host$tag_http_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path,http_host fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_path",
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{http_path}}",
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_host, http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_host$tag_http_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path,http_host fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 17 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_path",
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{http_path}}",
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 23 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_host, http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_host$tag_http_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path,http_host fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 28 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_path",
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{http_path}}",
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 34 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_host, http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_host$tag_http_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path,http_host fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 39 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_path",
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{http_path}}",
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 45 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 45 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_host, http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_host$tag_http_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path,http_host fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 50 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 50 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Incoming Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 56 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_path",
     "expr": "(sum(increase(http_in_responsetime_sum{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval])) by (http_path)) >= 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{http_path}}",
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "singlestat",
   "description": "Incoming HTTP Requests per second for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "singlestat",
   "description": "The error rate of incoming http requests for the selected endpoints and applications",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 56 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_in_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_in_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_in_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(label_join(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]), \"http_url\", \"\", \"http_host\", \"http_path\")) by (http_url) > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM (\n SELECT  SUM(total) as za_requests, SUM(times) / SUM(total) AS zb_response_time, SUM(errors) / SUM(total) AS zc_error_rate FROM (\n      SELECT spread(\"counter\") AS total,spread(\"errorcounter\")AS errors, spread(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/ AND application =~ /^$application$/ AND http_path =~ /^$path$/  GROUP BY *) GROUP BY http_host, http_path fill(0)\n) WHERE za_requests > 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outgoing Avg. Response Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_http_host$tag_http_path",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(times) / SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"timesum\") AS times FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY  *) \nWHERE total > 0\nGROUP BY time($__interval), http_path,http_host fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Req / Sec",
   "type": "singlestat",
   "description": "Outgoing HTTP Requests per second issued towards the selected endpoints from the given application",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 61 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(total)/$__interval_ms*1000 AS value FROM (\n      SELECT difference(\"counter\") AS total FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service$/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY * ) \nGROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Out Error Rate",
   "type": "singlestat",
   "description": "The error rate of outgoing http requests issued towards the selected endpoints of the selected application",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 61 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(increase(http_out_count{http_status!~\"(1|2|3)\\\\d\\\\d\",service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range]))\n/ sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) >= 0)\nor (sum(increase(http_out_count{service=\"$service\",application=~\"$application\",http_path=~\"$path\"}[$__range])) > 0) * 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  SUM(errors)/SUM(total) AS value FROM (\n      SELECT difference(\"counter\") AS total, difference(\"errorcounter\") AS errors FROM \"http_out_joined\" \n      WHERE $timeFilter AND service =~ /^$service/  AND application=~ /^$application$/  AND http_path=~ /^$path$/ GROUP BY *) \nGROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}