{
 "title": "inspectIT Agent Self-Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "SHOW TAG VALUES WITH KEY = \"service\""
   }
  ]
 },
 "panels": [
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"instrumented\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - LAST(\"queuesize\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "JVM CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"instrumented\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 8 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - LAST(\"queuesize\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "JVM CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"instrumented\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 15 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 15 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - LAST(\"queuesize\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "JVM CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"instrumented\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 22 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 22 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - LAST(\"queuesize\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "JVM CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 29 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"instrumented\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 29 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 29 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - LAST(\"queuesize\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "JVM CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  { "title": "$service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Instr. Scope",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LAST(\"instrumented\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 36 },
   "targets": [
    {
     "alias": "# classes loaded by JVM",
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# instrumented classes",
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "# classes pending for analysis",
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Analysis Progress",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 36 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 1 - LAST(\"queuesize\")/LAST(\"loaded\") FROM instrumentation_state WHERE $timeFilter AND service =~ /^$service/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instrumentation State over time (Logarithmic Scale)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "# Classes" }
   ],
   "targets": [
    {
     "alias": "loaded classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_classes_loaded",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "instrumented classes",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumented_classes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "classes pending for analysis",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspectit_self_instrumentation_queue_size",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "alias": "JVM CPU Utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}